<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>ToolBox</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>ToolBox</AssemblyTitle>
    <Product>ToolBox</Product>
    <Description>带简介的本地程序目录</Description>
    <Version>0.1.0</Version>
    <ApplicationIcon>asset\ToolBox.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**" />
    <None Remove="tests/**" />
  </ItemGroup>

</Project>

